### PR TITLE
Feat/update helm chart

### PR DESCRIPTION
**Pull request by energyaccountnr1**

### CODE REVIEW

**Comment by energyaccountnr1** [comment]
We like to use the new 4.x version. Not sure if this is the way to get a updated helm template

**Comment by cosmic-flood** [comment]
@dsun0720

**Comment by AmyJeanes** [comment]
Hey, is there any update on this, I'd love to see an update to the new version (and also my change in https://github.com/featbit/featbit-charts/pull/40 published 😄)

**Comment by selfisch** [comment]
Hello there,
any updates on this? Is there anything we can support this pr?
Is there maybe a new prerelease helm-chart version we can test in our dev environment?
Have a nice one

**Comment by AmyJeanes** [comment]
Hey @deleteLater / @dsun0720, the app version is now from the 23rd May, nearly 6 months ago - can we please upgrade this chart to the latest version of the app?

Also @energyaccountnr1 we can probably bump this up to v4.1.1 now

**Review by dsun0720 — APPROVED** [review]

**Pull request merged**
